# Local development services.
#
# To activate this feature, follow the instructions at the top of the
# 'example.settings.local.php' file, which sits next to this file.
parameters:
  http.response.debug_cacheability_headers: true
  twig.config:
    debug: true
    auto_reload: true
    cache: false
  #services:
  #cache.backend.null:
  #class: Drupal\Core\Cache\NullBackendFactory
  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders: ["x-csrf-token", "authorization", "content-type", "accept", "origin", "x-requested-with", "access-control-allow-origin", "x-allowed-header"]
    # Specify allowed request methods, specify ['*'] to allow all possible ones.
    allowedMethods: ["GET"]
    # Configure requests allowed from specific origins.
    allowedOrigins: ["http://flowpanama.com"]
    # Sets the Access-Control-Expose-Headers header.
    exposedHeaders: true
    # Sets the Access-Control-Max-Age header.
    maxAge: 1000
    # Sets the Access-Control-Allow-Credentials header.
    supportsCredentials: true
services:
  cache.backend.null:
    class: Drupal\Core\Cache\NullBackendFactory
